version: '3.8'

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: progetto
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./back-end
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/progetto?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  frontend:
    build: ./front-end
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql-data:
